# Use an official Node runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy only the package.json and package-lock.json (or yarn.lock) to utilize cache
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm ci

# Install nodemon
RUN npm i -g nodemon
RUN npm i -g next

# Copy the rest of the current directory contents into the container at /usr/src/app
COPY . .

# Ensure the node_modules/.bin directory is in the PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run npm run dev when the container launches
CMD ["npm", "run", "dev"]
