services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:  # Added line for specifying an environment file
      - .env.fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
